export const booleanColumns = [
  'Sides',
  'Subluxation',
  'Muscle Spasm',
  'Trigger Points',
  'Tenderness',
  'Numbness',
  'Edema',
  'Swelling',
  'Reduced Motion',
];
export const spinalLevels = [
  'occ_c1',
  'c1_c2',
  'c2_c3',
  'c3_c4',
  'c4_c5',
  'c5_c6',
  'c6_c7',
  'c7_t1',
  't1_t2',
  't2_t3',
  't3_t4',
  't4_t5',
  't5_t6',
  't6_t7',
  't7_t8',
  't8_t9',
  't9_t10',
  't10_t11',
  't11_t12',
  't12_l1',
  'l1_l2',
  'l2_l3',
  'l3_l4',
  'l4_l5',
  'l5_s1',
  's1_s2',
  's2_s3',
  's3_s4',
  's4_s5',
  's5_',
];
export const extremityLevels = [
  'shoulder',
  'arm',
  'bicep',
  'tricep',
  'elbow',
  'wrist',
  'hand',
  'hip',
  'thigh',
  'leg',
  'knee',
  'calf',
  'ankle',
  'foot',
];
export const entryFields = [
  'side',
  'sublux',
  'muscleSpasm',
  'triggerPoints',
  'tenderness',
  'numbness',
  'edema',
  'swelling',
  'reducedMotion',
];
export const treatmentFields = [
  'side',
  'physioPositioning', // this will be one of treatmentOptions, so if it does not have a value it will be null, otherwise this field will have a value that is one of treatmentOptions
  'coldPack',
  'hotPack',
  'electStim',
  'traction',
  'massage',
  'treatmentPositioning', // this will be one of treatmentOptions, so if it does not have a value it will be null, otherwise this field will have a value that is one of treatmentOptions
  'treatmentTechnique', // this will be one of treatmentOptions, so if it does not have a value it will be null, otherwise this field will have a value that is one of treatmentOptions
  'treatmentManipulation',
];
export const camelCaseColumns = {
  Sides: 'sides',
  Subluxation: 'subluxation',
  'Muscle Spasm': 'muscleSpasm',
  'Trigger Points': 'triggerPoints',
  Tenderness: 'tenderness',
  Numbness: 'numbness',
  Edema: 'edema',
  Swelling: 'swelling',
  'Reduced Motion': 'reducedMotion',
};
