// Comprehensive demo data for all entities

export const demoPatients = [
  {
    id: 1,
    acctNo: 'PT001',
    firstName: 'John',
    lastName: 'Smith',
    middleName: 'Michael',
    phoneNumber: '555-0123',
    email: 'john.smith@email.com',
    dateOfBirth: '1985-03-15',
    address: '123 Main St, Springfield',
    heightFeet: 6,
    heightInches: 2,
    weight: 185,
    nextAppointment: new Date('2024-12-15'),
    lastUpdated: new Date('2024-12-05'),
    createdDate: new Date('2024-01-10'),
  },
  {
    id: 2,
    acctNo: 'PT002',
    firstName: 'Maria',
    lastName: 'Garcia',
    middleName: 'Elena',
    phoneNumber: '555-0456',
    email: 'maria.garcia@email.com',
    dateOfBirth: '1990-07-22',
    address: '456 Oak Ave, Springfield',
    heightFeet: 5,
    heightInches: 6,
    weight: 140,
    nextAppointment: new Date('2024-12-12'),
    lastUpdated: new Date('2024-12-07'),
    createdDate: new Date('2024-02-15'),
  },
  {
    id: 3,
    acctNo: 'PT003',
    firstName: 'David',
    lastName: 'Johnson',
    middleName: 'Robert',
    phoneNumber: '555-0789',
    email: 'david.j@email.com',
    dateOfBirth: '1978-11-30',
    address: '789 Pine Rd, Springfield',
    heightFeet: 5,
    heightInches: 10,
    weight: 175,
    nextAppointment: new Date('2024-12-18'),
    lastUpdated: new Date('2024-12-06'),
    createdDate: new Date('2024-03-20'),
  },
  {
    id: 4,
    acctNo: 'PT004',
    firstName: 'Lisa',
    lastName: 'Williams',
    middleName: 'Ann',
    phoneNumber: '555-0321',
    email: 'lisa.w@email.com',
    dateOfBirth: '1995-02-18',
    address: '321 Elm St, Springfield',
    heightFeet: 5,
    heightInches: 4,
    weight: 125,
    nextAppointment: new Date('2024-12-10'),
    lastUpdated: new Date('2024-12-08'),
    createdDate: new Date('2024-04-05'),
  },
  {
    id: 5,
    acctNo: 'PT005',
    firstName: 'Robert',
    lastName: 'Brown',
    middleName: 'James',
    phoneNumber: '555-0654',
    email: 'robert.brown@email.com',
    dateOfBirth: '1982-09-05',
    address: '654 Maple Dr, Springfield',
    heightFeet: 6,
    heightInches: 0,
    weight: 190,
    nextAppointment: new Date('2024-12-20'),
    lastUpdated: new Date('2024-12-04'),
    createdDate: new Date('2024-05-12'),
  },
];

// Patient Complaints
export const demoComplaints = [
  {
    id: 'complaint-1',
    patientId: 1,
    text: 'Lower back pain radiating down right leg',
    painLevel: 7,
    lastEdited: new Date('2024-12-05'),
  },
  {
    id: 'complaint-2',
    patientId: 1,
    text: 'Neck stiffness and reduced mobility',
    painLevel: 5,
    lastEdited: new Date('2024-12-05'),
  },
  {
    id: 'complaint-3',
    patientId: 2,
    text: 'Chronic headaches, especially in morning',
    painLevel: 6,
    lastEdited: new Date('2024-12-07'),
  },
  {
    id: 'complaint-4',
    patientId: 2,
    text: 'Shoulder tension and limited range of motion',
    painLevel: 4,
    lastEdited: new Date('2024-12-07'),
  },
  {
    id: 'complaint-5',
    patientId: 3,
    text: 'Mid-back pain after prolonged sitting',
    painLevel: 5,
    lastEdited: new Date('2024-12-06'),
  },
  {
    id: 'complaint-6',
    patientId: 4,
    text: 'Right hip pain when walking',
    painLevel: 6,
    lastEdited: new Date('2024-12-08'),
  },
  {
    id: 'complaint-7',
    patientId: 4,
    text: 'Tingling sensation in left arm',
    painLevel: 3,
    lastEdited: new Date('2024-12-08'),
  },
  {
    id: 'complaint-8',
    patientId: 5,
    text: 'Upper back tightness and spasms',
    painLevel: 7,
    lastEdited: new Date('2024-12-04'),
  },
];

// Treatment Notes - Full Demo Data
export const demoNotes = [
  {
    id: 'note-1',
    patientId: 1,
    visitDate: new Date('2024-12-05'),
    visitDateText: '12/05/2024',
    temperature: 98.6,
    pulse: 72,
    systolic: 120,
    diastolic: 80,
    respiration: 16,
    physiotherapy: 15,
    physio: 10,
    tx: 5,
    phaseOneRoomAssignment: 'Room 1',
    phaseTwoRoomAssignment: 'Room 2',
    phaseThreeRoomAssignment: 'Treatment A',
    phaseFourRoomAssignment: 'Final',
    doctorNote:
      'Patient showing improvement in lumbar mobility. Continue current treatment protocol. Recommended home stretching exercises. Subluxation at L4-L5 addressed with diversified technique. Patient tolerated treatment well.',
    otherNotes:
      'Patient reports 30% reduction in pain since last visit. Compliance with home exercise program good.',
    createdDate: new Date('2024-12-05'),
    lastEdited: new Date('2024-12-05'),
  },
  {
    id: 'note-2',
    patientId: 2,
    visitDate: new Date('2024-12-07'),
    visitDateText: '12/07/2024',
    temperature: 98.4,
    pulse: 68,
    systolic: 115,
    diastolic: 75,
    respiration: 14,
    physiotherapy: 20,
    physio: 12,
    tx: 8,
    phaseOneRoomAssignment: 'Room 3',
    phaseTwoRoomAssignment: 'Room 1',
    phaseThreeRoomAssignment: 'Treatment B',
    phaseFourRoomAssignment: 'Recovery',
    doctorNote:
      'Cervical adjustment well-tolerated. Patient reports significant relief from headaches. Muscle tension reduced in upper trapezius.',
    otherNotes:
      'Scheduled follow-up in 1 week. Patient compliant with treatment plan.',
    createdDate: new Date('2024-12-07'),
    lastEdited: new Date('2024-12-07'),
  },
  {
    id: 'note-3',
    patientId: 3,
    visitDate: new Date('2024-12-06'),
    visitDateText: '12/06/2024',
    temperature: 98.7,
    pulse: 75,
    systolic: 125,
    diastolic: 82,
    respiration: 15,
    physiotherapy: 18,
    physio: 10,
    tx: 8,
    phaseOneRoomAssignment: 'Room 2',
    phaseTwoRoomAssignment: 'Room 4',
    phaseThreeRoomAssignment: 'Treatment A',
    phaseFourRoomAssignment: 'Final',
    doctorNote:
      'Mid-thoracic adjustment performed. Patient tolerated treatment well. Recommending ergonomic assessment for workspace.',
    otherNotes: 'Patient interested in preventive care program.',
    createdDate: new Date('2024-12-06'),
    lastEdited: new Date('2024-12-06'),
  },
  {
    id: 'note-4',
    patientId: 4,
    visitDate: new Date('2024-12-08'),
    visitDateText: '12/08/2024',
    temperature: 98.5,
    pulse: 70,
    systolic: 118,
    diastolic: 76,
    respiration: 16,
    physiotherapy: 22,
    physio: 14,
    tx: 8,
    phaseOneRoomAssignment: 'Room 1',
    phaseTwoRoomAssignment: 'Room 3',
    phaseThreeRoomAssignment: 'Treatment C',
    phaseFourRoomAssignment: 'Recovery',
    doctorNote:
      'Hip mobility improving. Applied soft tissue techniques to gluteal region. Patient advised on proper stretching protocol.',
    otherNotes: 'Patient responding well to treatment. Continue current plan.',
    createdDate: new Date('2024-12-08'),
    lastEdited: new Date('2024-12-08'),
  },
  {
    id: 'note-5',
    patientId: 5,
    visitDate: new Date('2024-12-04'),
    visitDateText: '12/04/2024',
    temperature: 98.8,
    pulse: 78,
    systolic: 130,
    diastolic: 85,
    respiration: 17,
    physiotherapy: 16,
    physio: 10,
    tx: 6,
    phaseOneRoomAssignment: 'Room 4',
    phaseTwoRoomAssignment: 'Room 2',
    phaseThreeRoomAssignment: 'Treatment B',
    phaseFourRoomAssignment: 'Final',
    doctorNote:
      'Upper thoracic restrictions addressed. Muscle spasms reduced significantly. Patient education on posture and ergonomics provided.',
    otherNotes: 'Patient committed to home exercise program.',
    createdDate: new Date('2024-12-04'),
    lastEdited: new Date('2024-12-04'),
  },
];

// Reports (Exam Summaries)
export const demoReports = [
  {
    id: 'report-1',
    patientId: 1,
    exam_date: new Date('2024-11-20'),
    temp: 98.6,
    sys: 120,
    dia: 80,
    pulse: 72,
    resp: 16,
    speech: 'Clear and coherent',
    gait: 'Antalgic gait favoring right side',
    rhomberg: 'Negative',
    demeanor: 'Alert and cooperative',
    dateAdded: new Date('2024-11-20'),
  },
  {
    id: 'report-2',
    patientId: 2,
    exam_date: new Date('2024-11-25'),
    temp: 98.4,
    sys: 115,
    dia: 75,
    pulse: 68,
    resp: 14,
    speech: 'Clear',
    gait: 'Normal, steady',
    rhomberg: 'Negative',
    demeanor: 'Pleasant, engaged',
    dateAdded: new Date('2024-11-25'),
  },
  {
    id: 'report-3',
    patientId: 3,
    exam_date: new Date('2024-11-28'),
    temp: 98.7,
    sys: 125,
    dia: 82,
    pulse: 75,
    resp: 15,
    speech: 'Normal',
    gait: 'Slightly guarded',
    rhomberg: 'Negative',
    demeanor: 'Cooperative',
    dateAdded: new Date('2024-11-28'),
  },
];

// Settings - Rooms
export const demoRooms = [
  { id: 1, text: 'Room 1', lastEdited: new Date(), createdAt: new Date() },
  { id: 2, text: 'Room 2', lastEdited: new Date(), createdAt: new Date() },
  { id: 3, text: 'Room 3', lastEdited: new Date(), createdAt: new Date() },
  { id: 4, text: 'Room 4', lastEdited: new Date(), createdAt: new Date() },
  { id: 5, text: 'Treatment A', lastEdited: new Date(), createdAt: new Date() },
  { id: 6, text: 'Treatment B', lastEdited: new Date(), createdAt: new Date() },
  { id: 7, text: 'Treatment C', lastEdited: new Date(), createdAt: new Date() },
  { id: 8, text: 'Recovery', lastEdited: new Date(), createdAt: new Date() },
  { id: 9, text: 'Final', lastEdited: new Date(), createdAt: new Date() },
];

// Demo Entries - Spinal Adjustments
export const demoSpinalEntries = [
  {
    id: 'spinal-entry-1',
    noteId: 'note-1',
    spinalLevel: 'C1',
    side: 'Left',
    sublux: true,
    muscleSpasm: true,
    triggerPoints: false,
    tenderness: true,
    numbness: false,
    edema: false,
    swelling: false,
    reducedMotion: true,
    physioPositioning: 'Supine Position',
    coldPack: true,
    hotPack: false,
    electricalStimulation: true,
    ultrasound: false,
    traction: false,
    massage: true,
    stretching: true,
    exercise: false,
    treatmentPositioning: 'Manual Adjustment',
    treatmentTechnique: 'Diversified Technique',
  },
  {
    id: 'spinal-entry-2',
    noteId: 'note-1',
    spinalLevel: 'L4',
    side: 'Right',
    sublux: true,
    muscleSpasm: true,
    triggerPoints: true,
    tenderness: true,
    numbness: false,
    edema: false,
    swelling: false,
    reducedMotion: true,
    physioPositioning: 'Prone Position',
    coldPack: false,
    hotPack: true,
    electricalStimulation: true,
    ultrasound: true,
    traction: false,
    massage: true,
    stretching: true,
    exercise: true,
    treatmentPositioning: 'Flexion-Distraction',
    treatmentTechnique: 'Cox Flexion-Distraction',
  },
];

// Demo Extremity Entries
export const demoExtremityEntries = [
  {
    id: 'extremity-entry-1',
    noteId: 'note-4',
    extremityLevel: 'Right Hip',
    side: 'Right',
    sublux: false,
    muscleSpasm: true,
    triggerPoints: true,
    tenderness: true,
    numbness: false,
    edema: false,
    swelling: true,
    reducedMotion: true,
    physioPositioning: 'Side-Lying (Right)',
    coldPack: true,
    hotPack: false,
    electricalStimulation: false,
    ultrasound: true,
    traction: false,
    massage: true,
    stretching: true,
    exercise: true,
    treatmentPositioning: 'Manual Adjustment',
    treatmentTechnique: 'Soft Tissue Mobilization',
  },
];

// Settings - Treatment Options
export const demoTreatmentOptions = [
  // Physio Positioning
  {
    id: 1,
    text: 'Supine Position',
    category: 'physioPositioning',
    lastEdited: new Date(),
    createdAt: new Date(),
  },
  {
    id: 2,
    text: 'Prone Position',
    category: 'physioPositioning',
    lastEdited: new Date(),
    createdAt: new Date(),
  },
  {
    id: 3,
    text: 'Side-Lying (Left)',
    category: 'physioPositioning',
    lastEdited: new Date(),
    createdAt: new Date(),
  },
  {
    id: 4,
    text: 'Side-Lying (Right)',
    category: 'physioPositioning',
    lastEdited: new Date(),
    createdAt: new Date(),
  },
  {
    id: 5,
    text: 'Seated',
    category: 'physioPositioning',
    lastEdited: new Date(),
    createdAt: new Date(),
  },
  // Treatment Positioning
  {
    id: 6,
    text: 'Flexion-Distraction',
    category: 'treatmentPositioning',
    lastEdited: new Date(),
    createdAt: new Date(),
  },
  {
    id: 7,
    text: 'Drop Table',
    category: 'treatmentPositioning',
    lastEdited: new Date(),
    createdAt: new Date(),
  },
  {
    id: 8,
    text: 'Manual Adjustment',
    category: 'treatmentPositioning',
    lastEdited: new Date(),
    createdAt: new Date(),
  },
  {
    id: 9,
    text: 'Activator',
    category: 'treatmentPositioning',
    lastEdited: new Date(),
    createdAt: new Date(),
  },
  // Treatment Techniques
  {
    id: 10,
    text: 'Diversified Technique',
    category: 'treatmentTechnique',
    lastEdited: new Date(),
    createdAt: new Date(),
  },
  {
    id: 11,
    text: 'Gonstead Technique',
    category: 'treatmentTechnique',
    lastEdited: new Date(),
    createdAt: new Date(),
  },
  {
    id: 12,
    text: 'Thompson Technique',
    category: 'treatmentTechnique',
    lastEdited: new Date(),
    createdAt: new Date(),
  },
  {
    id: 13,
    text: 'Cox Flexion-Distraction',
    category: 'treatmentTechnique',
    lastEdited: new Date(),
    createdAt: new Date(),
  },
  {
    id: 14,
    text: 'Activator Method',
    category: 'treatmentTechnique',
    lastEdited: new Date(),
    createdAt: new Date(),
  },
  {
    id: 15,
    text: 'Soft Tissue Mobilization',
    category: 'treatmentTechnique',
    lastEdited: new Date(),
    createdAt: new Date(),
  },
];

// Treatment Method Names
export const demoTreatmentMethodNames = [
  { id: 1, name: 'Cold Pack' },
  { id: 2, name: 'Hot Pack' },
  { id: 3, name: 'Electrical Stimulation' },
  { id: 4, name: 'Ultrasound' },
  { id: 5, name: 'Traction' },
  { id: 6, name: 'Massage Therapy' },
  { id: 7, name: 'Stretching' },
  { id: 8, name: 'Exercise Therapy' },
];

// Treatment Plan Options
export const demoTreatmentPlanOptions = [
  { id: 1, text: 'Continue current treatment protocol' },
  { id: 2, text: 'Increase frequency to 3x per week' },
  { id: 3, text: 'Reduce frequency to 1x per week' },
  { id: 4, text: 'Add home exercise program' },
  { id: 5, text: 'Schedule re-examination in 4 weeks' },
  { id: 6, text: 'Maintain maintenance care schedule' },
  { id: 7, text: 'Refer for additional imaging' },
  { id: 8, text: 'Co-management with physical therapy' },
];

// Get all demo data for a specific patient
export function getPatientDemoData(patientId: number) {
  return {
    patient: demoPatients.find((p) => p.id === patientId),
    complaints: demoComplaints.filter((c) => c.patientId === patientId),
    notes: demoNotes.filter((n) => n.patientId === patientId),
    reports: demoReports.filter((r) => r.patientId === patientId),
  };
}

// Get all settings data
export function getAllSettingsData() {
  return {
    rooms: demoRooms,
    treatmentOptions: demoTreatmentOptions,
    treatmentMethodNames: demoTreatmentMethodNames,
    treatmentPlanOptions: demoTreatmentPlanOptions,
  };
}
