export const cellMappings = {
  A1: 'Patient Name',
  B1: (payload) => payload.patientFirstName,
  C1: (payload) => payload.patientLastName,
  D1: '',
  E1: 'Note Visit Date',
  F1: (payload) => payload.noteVisitDate,
  G1: '',
  H1: '',
  I1: '',
  J1: '',
  K1: '',
  L1: '',
  M1: '',
  N1: '',
  O1: '',
  P1: '',
  Q1: '',
  R1: '',
  S1: '',
  T1: '',
  U1: '',
  V1: '',
  W1: '',
  X1: '',
  Y1: '',
  Z1: '',
  AA1: '',
  AB1: '',
  AC1: '',
  A2: '',
  B2: '',
  C2: '',
  D2: '',
  E2: '',
  F2: (payload) => payload.height,
  G2: '',
  H2: '',
  I2: '',
  J2: '',
  K2: '',
  L2: '',
  M2: '',
  N2: '',
  O2: (payload) => payload.weight,
  P2: '',
  Q2: '',
  R2: (payload) => payload.temperature,
  S2: '',
  T2: '',
  U2: (payload) => payload.systolic,
  V2: '',
  W2: '',
  X2: (payload) => payload.diastolic,
  Y2: '',
  Z2: '',
  AA2: (payload) => payload.pulse,
  AB2: '',
  AC2: (payload) => payload.respiration,
  A3: 'VITALS:',
  B3: '',
  C3: '',
  D3: '',
  E3: '',
  F3: 'Height',
  G3: '',
  H3: '',
  I3: '',
  J3: '',
  K3: '',
  L3: '',
  M3: '',
  N3: '',
  O3: 'Weight',
  P3: '',
  Q3: '',
  R3: 'Temperature',
  S3: '',
  T3: '',
  U3: 'Systolic',
  V3: '',
  W3: '',
  X3: 'Diastolic',
  Y3: '',
  Z3: '',
  AA3: 'Pulse',
  AB3: '',
  AC3: 'Respiration',
  A4: '',
  B4: '',
  C4: '',
  D4: '',
  E4: '',
  F4: '',
  G4: '',
  H4: '',
  I4: '',
  J4: '',
  K4: '',
  L4: '',
  M4: '',
  N4: '',
  O4: '',
  P4: '',
  Q4: '',
  R4: '',
  S4: '',
  T4: '',
  U4: '',
  V4: '',
  W4: '',
  X4: '',
  Y4: '',
  Z4: '',
  AA4: '',
  AB4: '',
  AC4: '',
  A5: 'PHYSIOTHERAPY #:',
  B5: '',
  C5: (payload) => payload.physiotherapyNumber,
  D5: '',
  E5: '',
  F5: '',
  G5: '',
  H5: '',
  I5: '',
  J5: '',
  K5: '',
  L5: '',
  M5: 'ROOM ASSIGNMENTS:',
  N5: '',
  O5: '',
  P5: '',
  Q5: '',
  R5: '',
  S5: '',
  T5: 'Physio:',
  U5: (payload) => payload.phaseOneRoomAssignments.physio || '',
  V5: '',
  W5: '',
  X5: '',
  Y5: '',
  Z5: '',
  AA5: 'TX:',
  AB5: (payload) => payload.phaseOneRoomAssignments.tx || '',
  AC5: '',
  A6: '',
  B6: '',
  C6: '',
  D6: '',
  E6: '',
  F6: '',
  G6: '',
  H6: '',
  I6: '',
  J6: '',
  K6: '',
  L6: '',
  M6: '',
  N6: '',
  O6: '',
  P6: '',
  Q6: '',
  R6: '',
  S6: '',
  T6: '',
  U6: '',
  V6: '',
  W6: '',
  X6: '',
  Y6: '',
  Z6: '',
  AA6: '',
  AB6: '',
  AC6: '',
  A7: 'SPINAL',
  B7: '',
  C7: '',
  D7: '',
  E7: 'SIDES',
  F7: '',
  G7: '',
  H7: '',
  I7: 'OBJECTIVE FINDINGS',
  J7: '',
  K7: '',
  L7: '',
  M7: '',
  N7: '',
  O7: '',
  P7: '',
  Q7: '',
  R7: 'PHYSIOTHERAPIES',
  S7: '',
  T7: '',
  U7: '',
  V7: '',
  W7: '',
  X7: '',
  Y7: '',
  Z7: '',
  AA7: 'TREATMENT',
  AB7: '',
  AC7: '',
  A8: 'LEVELS',
  B8: 'REGIONS',
  C8: '',
  D8: '',
  E8: 'L',
  F8: 'R',
  G8: 'B',
  H8: '',
  I8: 'SUBLUX',
  J8: 'MUSCLE SPASMS',
  K8: 'TRIGGER POINTS',
  L8: 'TENDERNESS',
  M8: 'NUMBNESS',
  N8: 'EDEMA',
  O8: 'SWELLING',
  P8: 'REDUCED MOTION',
  Q8: '',
  R8: 'POSITIONING',
  S8: 'COLD PACKS',
  T8: 'HOT PACKS',
  U8: '',
  V8: 'ELECT STIM',
  W8: '',
  X8: 'TRACTION',
  Y8: 'MASSAGE',
  Z8: '',
  AA8: 'POSITIONING',
  AB8: 'TECHNIQUES',
  AC8: 'MANIPULATION',
  // ...
  A10: 'OCC',
  B10: 'Sub. Occ',
  C10: 'Full C-Region',
  D10: '',
  E10: (payload) => payload.occ.sides.l || '',
  F10: (payload) => payload.occ.sides.r || '',
  G10: (payload) => payload.occ.sides.b || '',
  H10: '',
  I10: (payload) => payload.occ.of.sublux || '',
  J10: (payload) => payload.occ.of.muscleSpasm || '',
  K10: (payload) => payload.occ.of.triggerPoints || '',
  L10: (payload) => payload.occ.of.tenderness || '',
  M10: (payload) => payload.occ.of.numbness || '',
  N10: (payload) => payload.occ.of.edema || '',
  O10: (payload) => payload.occ.of.swelling || '',
  P10: (payload) => payload.occ.of.reducedMotion || '',
  Q10: '',
  R10: (payload) => payload.occ.physio.positioning || '',
  S10: (payload) => payload.occ.physio.coldPacks || '',
  T10: (payload) => payload.occ.physio.hotPacks || '',
  U10: '',
  V10: (payload) => payload.occ.physio.electStim || '',
  W10: '',
  X10: (payload) => payload.occ.physio.traction || '',
  Y10: (payload) => payload.occ.physio.massage || '',
  Z10: '',
  AA10: (payload) => payload.occ.treatment.positioning || '',
  AB10: (payload) => payload.occ.treatment.techniques || '',
  AC10: (payload) => payload.occ.treatment.manipulation || '',
  A11: 'C1',
  B11: '',
  C11: '',
  D11: '',
  E11: (payload) => payload.c1.sides.l || '',
  F11: (payload) => payload.c1.sides.r || '',
  G11: (payload) => payload.c1.sides.b || '',
  H11: '',
  I11: (payload) => payload.c1.of.sublux || '',
  J11: (payload) => payload.c1.of.muscleSpasm || '',
  K11: (payload) => payload.c1.of.triggerPoints || '',
  L11: (payload) => payload.c1.of.tenderness || '',
  M11: (payload) => payload.c1.of.numbness || '',
  N11: (payload) => payload.c1.of.edema || '',
  O11: (payload) => payload.c1.of.swelling || '',
  P11: (payload) => payload.c1.of.reducedMotion || '',
  Q11: '',
  R11: (payload) => payload.c1.physio.positioning || '',
  S11: (payload) => payload.c1.physio.coldPacks || '',
  T11: (payload) => payload.c1.physio.hotPacks || '',
  U11: '',
  V11: (payload) => payload.c1.physio.electStim || '',
  W11: '',
  X11: (payload) => payload.c1.physio.traction || '',
  Y11: (payload) => payload.c1.physio.massage || '',
  Z11: '',
  AA11: (payload) => payload.c1.treatment.positioning || '',
  AB11: (payload) => payload.c1.treatment.techniques || '',
  AC11: (payload) => payload.c1.treatment.manipulation || '',
  A12: 'C2',
  B12: 'Upper Cerv.',
  C12: '',
  D12: '',
  E12: (payload) => payload.c2.sides.l || '',
  F12: (payload) => payload.c2.sides.r || '',
  G12: (payload) => payload.c2.sides.b || '',
  H12: '',
  I12: (payload) => payload.c2.of.sublux || '',
  J12: (payload) => payload.c2.of.muscleSpasm || '',
  K12: (payload) => payload.c2.of.triggerPoints || '',
  L12: (payload) => payload.c2.of.tenderness || '',
  M12: (payload) => payload.c2.of.numbness || '',
  N12: (payload) => payload.c2.of.edema || '',
  O12: (payload) => payload.c2.of.swelling || '',
  P12: (payload) => payload.c2.of.reducedMotion || '',
  Q12: '',
  R12: (payload) => payload.c2.physio.positioning || '',
  S12: (payload) => payload.c2.physio.coldPacks || '',
  T12: (payload) => payload.c2.physio.hotPacks || '',
  U12: '',
  V12: (payload) => payload.c2.physio.electStim || '',
  W12: '',
  X12: (payload) => payload.c2.physio.traction || '',
  Y12: (payload) => payload.c2.physio.massage || '',
  Z12: '',
  AA12: (payload) => payload.c2.treatment.positioning || '',
  AB12: (payload) => payload.c2.treatment.techniques || '',
  AC12: (payload) => payload.c2.treatment.manipulation || '',
  A13: 'C3',
  B13: '',
  C13: '',
  D13: '',
  E13: (payload) => payload.c3.sides.l || '',
  F13: (payload) => payload.c3.sides.r || '',
  G13: (payload) => payload.c3.sides.b || '',
  H13: '',
  I13: (payload) => payload.c3.of.sublux || '',
  J13: (payload) => payload.c3.of.muscleSpasm || '',
  K13: (payload) => payload.c3.of.triggerPoints || '',
  L13: (payload) => payload.c3.of.tenderness || '',
  M13: (payload) => payload.c3.of.numbness || '',
  N13: (payload) => payload.c3.of.edema || '',
  O13: (payload) => payload.c3.of.swelling || '',
  P13: (payload) => payload.c3.of.reducedMotion || '',
  Q13: '',
  R13: (payload) => payload.c3.physio.positioning || '',
  S13: (payload) => payload.c3.physio.coldPacks || '',
  T13: (payload) => payload.c3.physio.hotPacks || '',
  U13: '',
  V13: (payload) => payload.c3.physio.electStim || '',
  W13: '',
  X13: (payload) => payload.c3.physio.traction || '',
  Y13: (payload) => payload.c3.physio.massage || '',
  Z13: '',
  AA13: (payload) => payload.c3.treatment.positioning || '',
  AB13: (payload) => payload.c3.treatment.techniques || '',
  AC13: (payload) => payload.c3.treatment.manipulation || '',
  A14: 'C4',
  B14: 'Mid Cerv.',
  C14: '',
  D14: '',
  E14: (payload) => payload.c4.sides.l || '',
  F14: (payload) => payload.c4.sides.r || '',
  G14: (payload) => payload.c4.sides.b || '',
  H14: '',
  I14: (payload) => payload.c4.of.sublux || '',
  J14: (payload) => payload.c4.of.muscleSpasm || '',
  K14: (payload) => payload.c4.of.triggerPoints || '',
  L14: (payload) => payload.c4.of.tenderness || '',
  M14: (payload) => payload.c4.of.numbness || '',
  N14: (payload) => payload.c4.of.edema || '',
  O14: (payload) => payload.c4.of.swelling || '',
  P14: (payload) => payload.c4.of.reducedMotion || '',
  Q14: '',
  R14: (payload) => payload.c4.physio.positioning || '',
  S14: (payload) => payload.c4.physio.coldPacks || '',
  T14: (payload) => payload.occ.physio.hotPacks || '',
  U14: '',
  V14: (payload) => payload.occ.physio.electStim || '',
  W14: '',
  X14: (payload) => payload.occ.physio.traction || '',
  Y14: (payload) => payload.occ.physio.massage || '',
  Z14: '',
  AA14: (payload) => payload.occ.treatment.positioning || '',
  AB14: (payload) => payload.occ.treatment.techniques || '',
  AC14: (payload) => payload.occ.treatment.manipulation || '',
  A15: 'C5',
  B15: '',
  C15: '',
  D15: '',
  E15: (payload) => payload.c5.sides.l || '',
  F15: (payload) => payload.c5.sides.r || '',
  G15: (payload) => payload.c5.sides.b || '',
  H15: '',
  I15: (payload) => payload.c5.of.sublux || '',
  J15: (payload) => payload.c5.of.muscleSpasm || '',
  K15: (payload) => payload.c5.of.triggerPoints || '',
  L15: (payload) => payload.c5.of.tenderness || '',
  M15: (payload) => payload.c5.of.numbness || '',
  N15: (payload) => payload.c5.of.edema || '',
  O15: (payload) => payload.c5.of.swelling || '',
  P15: (payload) => payload.c5.of.reducedMotion || '',
  Q15: '',
  R15: (payload) => payload.c5.physio.positioning || '',
  S15: (payload) => payload.c5.physio.coldPacks || '',
  T15: (payload) => payload.c5.physio.hotPacks || '',
  U15: '',
  V15: (payload) => payload.c5.physio.electStim || '',
  W15: '',
  X15: (payload) => payload.c5.physio.traction || '',
  Y15: (payload) => payload.c5.physio.massage || '',
  Z15: '',
  AA15: (payload) => payload.c5.treatment.positioning || '',
  AB15: (payload) => payload.c5.treatment.techniques || '',
  AC15: (payload) => payload.c5.treatment.manipulation || '',
  A16: 'C6',
  B16: 'Lower Cerv.',
  C16: '',
  D16: '',
  E16: (payload) => payload.c6.sides.l || '',
  F16: (payload) => payload.c6.sides.r || '',
  G16: (payload) => payload.c6.sides.b || '',
  H16: '',
  I16: (payload) => payload.c6.of.sublux || '',
  J16: (payload) => payload.c6.of.muscleSpasm || '',
  K16: (payload) => payload.c6.of.triggerPoints || '',
  L16: (payload) => payload.c6.of.tenderness || '',
  M16: (payload) => payload.c6.of.numbness || '',
  N16: (payload) => payload.c6.of.edema || '',
  O16: (payload) => payload.c6.of.swelling || '',
  P16: (payload) => payload.c6.of.reducedMotion || '',
  Q16: '',
  R16: (payload) => payload.c6.physio.positioning || '',
  S16: (payload) => payload.c6.physio.coldPacks || '',
  T16: (payload) => payload.c6.physio.hotPacks || '',
  U16: '',
  V16: (payload) => payload.c6.physio.electStim || '',
  W16: '',
  X16: (payload) => payload.c6.physio.traction || '',
  Y16: (payload) => payload.c6.physio.massage || '',
  Z16: '',
  AA16: (payload) => payload.c6.treatment.positioning || '',
  AB16: (payload) => payload.c6.treatment.techniques || '',
  AC16: (payload) => payload.c6.treatment.manipulation || '',
  A17: 'C7',
  B17: '',
  C17: '',
  D17: '',
  E17: (payload) => payload.c7.sides.l || '',
  F17: (payload) => payload.c7.sides.r || '',
  G17: (payload) => payload.c7.sides.b || '',
  H17: '',
  I17: (payload) => payload.c7.of.sublux || '',
  J17: (payload) => payload.c7.of.muscleSpasm || '',
  K17: (payload) => payload.c7.of.triggerPoints || '',
  L17: (payload) => payload.c7.of.tenderness || '',
  M17: (payload) => payload.c7.of.numbness || '',
  N17: (payload) => payload.c7.of.edema || '',
  O17: (payload) => payload.c7.of.swelling || '',
  P17: (payload) => payload.c7.of.reducedMotion || '',
  Q17: '',
  R17: (payload) => payload.c7.physio.positioning || '',
  S17: (payload) => payload.c7.physio.coldPacks || '',
  T17: (payload) => payload.c7.physio.hotPacks || '',
  U17: '',
  V17: (payload) => payload.c7.physio.electStim || '',
  W17: '',
  X17: (payload) => payload.c7.physio.traction || '',
  Y17: (payload) => payload.c7.physio.massage || '',
  Z17: '',
  AA17: (payload) => payload.c7.treatment.positioning || '',
  AB17: (payload) => payload.c7.treatment.techniques || '',
  AC17: (payload) => payload.c7.treatment.manipulation || '',
  A18: '',
  B18: '',
  C18: '',
  D18: '',
  E18: '',
  F18: '',
  G18: '',
  H18: '',
  I18: '',
  J18: '',
  K18: '',
  L18: '',
  M18: '',
  N18: '',
  O18: '',
  P18: '',
  Q18: '',
  R18: '',
  S18: '',
  T18: '',
  U18: '',
  V18: '',
  W18: '',
  X18: '',
  Y18: '',
  Z18: '',
  AA18: '',
  AB18: '',
  AC18: '',
  A19: 'T1',
  B19: 'Upper T',
  C19: 'Full T-Region',
  D19: '',
  E19: (payload) => payload.t1.sides.l || '',
  F19: (payload) => payload.t1.sides.r || '',
  G19: (payload) => payload.t1.sides.b || '',
  H19: '',
  I19: (payload) => payload.t1.of.sublux || '',
  J19: (payload) => payload.t1.of.muscleSpasm || '',
  K19: (payload) => payload.t1.of.triggerPoints || '',
  L19: (payload) => payload.t1.of.tenderness || '',
  M19: (payload) => payload.t1.of.numbness || '',
  N19: (payload) => payload.t1.of.edema || '',
  O19: (payload) => payload.t1.of.swelling || '',
  P19: (payload) => payload.t1.of.reducedMotion || '',
  Q19: '',
  R19: (payload) => payload.t1.physio.positioning || '',
  S19: (payload) => payload.t1.physio.coldPacks || '',
  T19: (payload) => payload.t1.physio.hotPacks || '',
  U19: '',
  V19: (payload) => payload.t1.physio.electStim || '',
  W19: '',
  X19: (payload) => payload.t1.physio.traction || '',
  Y19: (payload) => payload.t1.physio.massage || '',
  Z19: '',
  AA19: (payload) => payload.t1.treatment.positioning || '',
  AB19: (payload) => payload.t1.treatment.techniques || '',
  AC19: (payload) => payload.t1.treatment.manipulation || '',
  A20: 'T2',
  B20: '',
  C20: '',
  D20: '',
  E20: (payload) => payload.t2.sides.l || '',
  F20: (payload) => payload.t2.sides.r || '',
  G20: (payload) => payload.t2.sides.b || '',
  H20: '',
  I20: (payload) => payload.t2.of.sublux || '',
  J20: (payload) => payload.t2.of.muscleSpasm || '',
  K20: (payload) => payload.t2.of.triggerPoints || '',
  L20: (payload) => payload.t2.of.tenderness || '',
  M20: (payload) => payload.t2.of.numbness || '',
  N20: (payload) => payload.t2.of.edema || '',
  O20: (payload) => payload.t2.of.swelling || '',
  P20: (payload) => payload.t2.of.reducedMotion || '',
  Q20: '',
  R20: (payload) => payload.t2.physio.positioning || '',
  S20: (payload) => payload.t2.physio.coldPacks || '',
  T20: (payload) => payload.t2.physio.hotPacks || '',
  U20: '',
  V20: (payload) => payload.t2.physio.electStim || '',
  W20: '',
  X20: (payload) => payload.t2.physio.traction || '',
  Y20: (payload) => payload.t2.physio.massage || '',
  Z20: '',
  AA20: (payload) => payload.t2.treatment.positioning || '',
  AB20: (payload) => payload.t2.treatment.techniques || '',
  AC20: (payload) => payload.t2.treatment.manipulation || '',
  A21: 'T3',
  B21: '',
  C21: '',
  D21: '',
  E21: (payload) => payload.t3.sides.l || '',
  F21: (payload) => payload.t3.sides.r || '',
  G21: (payload) => payload.t3.sides.b || '',
  H21: '',
  I21: (payload) => payload.t3.of.sublux || '',
  J21: (payload) => payload.t3.of.muscleSpasm || '',
  K21: (payload) => payload.t3.of.triggerPoints || '',
  L21: (payload) => payload.t3.of.tenderness || '',
  M21: (payload) => payload.t3.of.numbness || '',
  N21: (payload) => payload.t3.of.edema || '',
  O21: (payload) => payload.t3.of.swelling || '',
  P21: (payload) => payload.t3.of.reducedMotion || '',
  Q21: '',
  R21: (payload) => payload.t3.physio.positioning || '',
  S21: (payload) => payload.t3.physio.coldPacks || '',
  T21: (payload) => payload.t3.physio.hotPacks || '',
  U21: '',
  V21: (payload) => payload.t3.physio.electStim || '',
  W21: '',
  X21: (payload) => payload.t3.physio.traction || '',
  Y21: (payload) => payload.t3.physio.massage || '',
  Z21: '',
  AA21: (payload) => payload.t3.treatment.positioning || '',
  AB21: (payload) => payload.t3.treatment.techniques || '',
  AC21: (payload) => payload.t3.treatment.manipulation || '',
  A22: 'T4',
  B22: 'Mid T',
  C22: '',
  D22: '',
  E22: (payload) => payload.t4.sides.l || '',
  F22: (payload) => payload.t4.sides.r || '',
  G22: (payload) => payload.t4.sides.b || '',
  H22: '',
  I22: (payload) => payload.t4.of.sublux || '',
  J22: (payload) => payload.t4.of.muscleSpasm || '',
  K22: (payload) => payload.t4.of.triggerPoints || '',
  L22: (payload) => payload.t4.of.tenderness || '',
  M22: (payload) => payload.t4.of.numbness || '',
  N22: (payload) => payload.t4.of.edema || '',
  O22: (payload) => payload.t4.of.swelling || '',
  P22: (payload) => payload.t4.of.reducedMotion || '',
  Q22: '',
  R22: (payload) => payload.t4.physio.positioning || '',
  S22: (payload) => payload.t4.physio.coldPacks || '',
  T22: (payload) => payload.t4.physio.hotPacks || '',
  U22: '',
  V22: (payload) => payload.t4.physio.electStim || '',
  W22: '',
  X22: (payload) => payload.t4.physio.traction || '',
  Y22: (payload) => payload.t4.physio.massage || '',
  Z22: '',
  AA22: (payload) => payload.t4.treatment.positioning || '',
  AB22: (payload) => payload.t4.treatment.techniques || '',
  AC22: (payload) => payload.t4.treatment.manipulation || '',
  A23: 'T5',
  B23: '',
  C23: '',
  D23: '',
  E23: (payload) => payload.t5.sides.l || '',
  F23: (payload) => payload.t5.sides.r || '',
  G23: (payload) => payload.t5.sides.b || '',
  H23: '',
  I23: (payload) => payload.t5.of.sublux || '',
  J23: (payload) => payload.t5.of.muscleSpasm || '',
  K23: (payload) => payload.t5.of.triggerPoints || '',
  L23: (payload) => payload.t5.of.tenderness || '',
  M23: (payload) => payload.t5.of.numbness || '',
  N23: (payload) => payload.t5.of.edema || '',
  O23: (payload) => payload.t5.of.swelling || '',
  P23: (payload) => payload.t5.of.reducedMotion || '',
  Q23: '',
  R23: (payload) => payload.t5.physio.positioning || '',
  S23: (payload) => payload.t5.physio.coldPacks || '',
  T23: (payload) => payload.t5.physio.hotPacks || '',
  U23: '',
  V23: (payload) => payload.t5.physio.electStim,
  W23: '',
  X23: (payload) => payload.t5.physio.traction,
  Y23: (payload) => payload.t5.physio.massage,
  Z23: '',
  AA23: (payload) => payload.t5.treatment.positioning,
  AB23: (payload) => payload.t5.treatment.techniques,
  AC23: (payload) => payload.t5.treatment.manipulation,
  A24: 'T6',
  B24: '',
  C24: '',
  D24: '',
  E24: (payload) => payload.t6.sides.l,
  F24: (payload) => payload.t6.sides.r,
  G24: (payload) => payload.t6.sides.b,
  H24: '',
  I24: (payload) => payload.t6.of.sublux,
  J24: (payload) => payload.t6.of.muscleSpasm,
  K24: (payload) => payload.t6.of.triggerPoints,
  L24: (payload) => payload.t6.of.tenderness,
  M24: (payload) => payload.t6.of.numbness,
  N24: (payload) => payload.t6.of.edema,
  O24: (payload) => payload.t6.of.swelling,
  P24: (payload) => payload.t6.of.reducedMotion,
  Q24: '',
  R24: (payload) => payload.t6.physio.positioning,
  S24: (payload) => payload.t6.physio.coldPacks,
  T24: (payload) => payload.t6.physio.hotPacks,
  U24: '',
  V24: (payload) => payload.t6.physio.electStim,
  W24: '',
  X24: (payload) => payload.t6.physio.traction,
  Y24: (payload) => payload.t6.physio.massage,
  Z24: '',
  AA24: (payload) => payload.t6.treatment.positioning,
  AB24: (payload) => payload.t6.treatment.techniques,
  AC24: (payload) => payload.t6.treatment.manipulation,
  A25: 'T7',
  B25: '',
  C25: '',
  D25: '',
  E25: (payload) => payload.t7.sides.l,
  F25: (payload) => payload.t7.sides.r,
  G25: (payload) => payload.t7.sides.b,
  H25: '',
  I25: (payload) => payload.t7.of.sublux,
  J25: (payload) => payload.t7.of.muscleSpasm,
  K25: (payload) => payload.t7.of.triggerPoints,
  L25: (payload) => payload.t7.of.tenderness,
  M25: (payload) => payload.t7.of.numbness,
  N25: (payload) => payload.t7.of.edema,
  O25: (payload) => payload.t7.of.swelling,
  P25: (payload) => payload.t7.of.reducedMotion,
  Q25: '',
  R25: (payload) => payload.t7.physio.positioning,
  S25: (payload) => payload.t7.physio.coldPacks,
  T25: (payload) => payload.t7.physio.hotPacks,
  U25: '',
  V25: (payload) => payload.t7.physio.electStim,
  W25: '',
  X25: (payload) => payload.t7.physio.traction,
  Y25: (payload) => payload.t7.physio.massage,
  Z25: '',
  AA25: (payload) => payload.t7.treatment.positioning,
  AB25: (payload) => payload.t7.treatment.techniques,
  AC25: (payload) => payload.t7.treatment.manipulation,
  A26: 'T8',
  B26: 'Lower T',
  C26: '',
  D26: '',
  E26: (payload) => payload.t8.sides.l,
  F26: (payload) => payload.t8.sides.r,
  G26: (payload) => payload.t8.sides.b,
  H26: '',
  I26: (payload) => payload.t8.of.sublux,
  J26: (payload) => payload.t8.of.muscleSpasm,
  K26: (payload) => payload.t8.of.triggerPoints,
  L26: (payload) => payload.t8.of.tenderness,
  M26: (payload) => payload.t8.of.numbness,
  N26: (payload) => payload.t8.of.edema,
  O26: (payload) => payload.t8.of.swelling,
  P26: (payload) => payload.t8.of.reducedMotion,
  Q26: '',
  R26: (payload) => payload.t8.physio.positioning,
  S26: (payload) => payload.t8.physio.coldPacks,
  T26: (payload) => payload.t8.physio.hotPacks,
  U26: '',
  V26: (payload) => payload.t8.physio.electStim,
  W26: '',
  X26: (payload) => payload.t8.physio.traction,
  Y26: (payload) => payload.t8.physio.massage,
  Z26: '',
  AA26: (payload) => payload.t8.treatment.positioning,
  AB26: (payload) => payload.t8.treatment.techniques,
  AC26: (payload) => payload.t8.treatment.manipulation,
  A27: 'T9',
  B27: '',
  C27: '',
  D27: '',
  E27: (payload) => payload.t9.sides.l,
  F27: (payload) => payload.t9.sides.r,
  G27: (payload) => payload.t9.sides.b,
  H27: '',
  I27: (payload) => payload.t9.of.sublux,
  J27: (payload) => payload.t9.of.muscleSpasm,
  K27: (payload) => payload.t9.of.triggerPoints,
  L27: (payload) => payload.t9.of.tenderness,
  M27: (payload) => payload.t9.of.numbness,
  N27: (payload) => payload.t9.of.edema,
  O27: (payload) => payload.t9.of.swelling,
  P27: (payload) => payload.t9.of.reducedMotion,
  Q27: '',
  R27: (payload) => payload.t9.physio.positioning,
  S27: (payload) => payload.t9.physio.coldPacks,
  T27: (payload) => payload.t9.physio.hotPacks,
  U27: '',
  V27: (payload) => payload.t9.physio.electStim,
  W27: '',
  X27: (payload) => payload.t9.physio.traction,
  Y27: (payload) => payload.t9.physio.massage,
  Z27: '',
  AA27: (payload) => payload.t9.treatment.positioning,
  AB27: (payload) => payload.t9.treatment.techniques,
  AC27: (payload) => payload.t9.treatment.manipulation,
  A28: 'T10',
  B28: '',
  C28: '',
  D28: '',
  E28: (payload) => payload.t10.sides.l,
  F28: (payload) => payload.t10.sides.r,
  G28: (payload) => payload.t10.sides.b,
  H28: '',
  I28: (payload) => payload.t10.of.sublux,
  J28: (payload) => payload.t10.of.muscleSpasm,
  K28: (payload) => payload.t10.of.triggerPoints,
  L28: (payload) => payload.t10.of.tenderness,
  M28: (payload) => payload.t10.of.numbness,
  N28: (payload) => payload.t10.of.edema,
  O28: (payload) => payload.t10.of.swelling,
  P28: (payload) => payload.t10.of.reducedMotion,
  Q28: '',
  R28: (payload) => payload.t10.physio.positioning,
  S28: (payload) => payload.t10.physio.coldPacks,
  T28: (payload) => payload.t10.physio.hotPacks,
  U28: '',
  V28: (payload) => payload.t10.physio.electStim,
  W28: '',
  X28: (payload) => payload.t10.physio.traction,
  Y28: (payload) => payload.t10.physio.massage,
  Z28: '',
  AA28: (payload) => payload.t10.treatment.positioning,
  AB28: (payload) => payload.t10.treatment.techniques,
  AC28: (payload) => payload.t10.treatment.manipulation,
  A29: 'T11',
  B29: '',
  C29: '',
  D29: '',
  E29: (payload) => payload.t11.sides.l,
  F29: (payload) => payload.t11.sides.r,
  G29: (payload) => payload.t11.sides.b,
  H29: '',
  I29: (payload) => payload.t11.of.sublux,
  J29: (payload) => payload.t11.of.muscleSpasm,
  K29: (payload) => payload.t11.of.triggerPoints,
  L29: (payload) => payload.t11.of.tenderness,
  M29: (payload) => payload.t11.of.numbness,
  N29: (payload) => payload.t11.of.edema,
  O29: (payload) => payload.t11.of.swelling,
  P29: (payload) => payload.t11.of.reducedMotion,
  Q29: '',
  R29: (payload) => payload.t11.physio.positioning,
  S29: (payload) => payload.t11.physio.coldPacks,
  T29: (payload) => payload.t11.physio.hotPacks,
  U29: '',
  V29: (payload) => payload.t11.physio.electStim,
  W29: '',
  X29: (payload) => payload.t11.physio.traction,
  Y29: (payload) => payload.t11.physio.massage,
  Z29: '',
  AA29: (payload) => payload.t11.treatment.positioning,
  AB29: (payload) => payload.t11.treatment.techniques,
  AC29: (payload) => payload.t11.treatment.manipulation,
  A30: 'T12',
  B30: '',
  C30: '',
  D30: '',
  E30: (payload) => payload.t12.sides.l,
  F30: (payload) => payload.t12.sides.r,
  G30: (payload) => payload.t12.sides.b,
  H30: '',
  I30: (payload) => payload.t12.of.sublux,
  J30: (payload) => payload.t12.of.muscleSpasm,
  K30: (payload) => payload.t12.of.triggerPoints,
  L30: (payload) => payload.t12.of.tenderness,
  M30: (payload) => payload.t12.of.numbness,
  N30: (payload) => payload.t12.of.edema,
  O30: (payload) => payload.t12.of.swelling,
  P30: (payload) => payload.t12.of.reducedMotion,
  Q30: '',
  R30: (payload) => payload.t12.physio.positioning,
  S30: (payload) => payload.t12.physio.coldPacks,
  T30: (payload) => payload.t12.physio.hotPacks,
  U30: '',
  V30: (payload) => payload.t12.physio.electStim,
  W30: '',
  X30: (payload) => payload.t12.physio.traction,
  Y30: (payload) => payload.t12.physio.massage,
  Z30: '',
  AA30: (payload) => payload.t12.treatment.positioning,
  AB30: (payload) => payload.t12.treatment.techniques,
  AC30: (payload) => payload.t12.treatment.manipulation,
  A31: '',
  B31: '',
  C31: '',
  D31: '',
  E31: '',
  F31: '',
  G31: '',
  H31: '',
  I31: '',
  J31: '',
  K31: '',
  L31: '',
  M31: '',
  N31: '',
  O31: '',
  P31: '',
  Q31: '',
  R31: '',
  S31: '',
  T31: '',
  U31: '',
  V31: '',
  W31: '',
  X31: '',
  Y31: '',
  Z31: '',
  AA31: '',
  AB31: '',
  AC31: '',
  A32: 'L1',
  B32: 'Upper L',
  C32: 'Full L-Region',
  D32: '',
  E32: (payload) => payload.l1.sides.l,
  F32: (payload) => payload.l1.sides.r,
  G32: (payload) => payload.l1.sides.b,
  H32: '',
  I32: (payload) => payload.l1.of.sublux,
  J32: (payload) => payload.l1.of.muscleSpasm,
  K32: (payload) => payload.l1.of.triggerPoints,
  L32: (payload) => payload.l1.of.tenderness,
  M32: (payload) => payload.l1.of.numbness,
  N32: (payload) => payload.l1.of.edema,
  O32: (payload) => payload.l1.of.swelling,
  P32: (payload) => payload.l1.of.reducedMotion,
  Q32: '',
  R32: (payload) => payload.l1.physio.positioning,
  S32: (payload) => payload.l1.physio.coldPacks,
  T32: (payload) => payload.l1.physio.hotPacks,
  U32: '',
  V32: (payload) => payload.l1.physio.electStim,
  W32: '',
  X32: (payload) => payload.l1.physio.traction,
  Y32: (payload) => payload.l1.physio.massage,
  Z32: '',
  AA32: (payload) => payload.l1.treatment.positioning,
  AB32: (payload) => payload.l1.treatment.techniques,
  AC32: (payload) => payload.l1.treatment.manipulation,
  A33: 'L2',
  B33: '',
  C33: '',
  D33: '',
  E33: (payload) => payload.l2.sides.l,
  F33: (payload) => payload.l2.sides.r,
  G33: (payload) => payload.l2.sides.b,
  H33: '',
  I33: (payload) => payload.l2.of.sublux,
  J33: (payload) => payload.l2.of.muscleSpasm,
  K33: (payload) => payload.l2.of.triggerPoints,
  L33: (payload) => payload.l2.of.tenderness,
  M33: (payload) => payload.l2.of.numbness,
  N33: (payload) => payload.l2.of.edema,
  O33: (payload) => payload.l2.of.swelling,
  P33: (payload) => payload.l2.of.reducedMotion,
  Q33: '',
  R33: (payload) => payload.l2.physio.positioning,
  S33: (payload) => payload.l2.physio.coldPacks,
  T33: (payload) => payload.l2.physio.hotPacks,
  U33: '',
  V33: (payload) => payload.l2.physio.electStim,
  W33: '',
  X33: (payload) => payload.l2.physio.traction,
  Y33: (payload) => payload.l2.physio.massage,
  Z33: '',
  AA33: (payload) => payload.l2.treatment.positioning,
  AB33: (payload) => payload.l2.treatment.techniques,
  AC33: (payload) => payload.l2.treatment.manipulation,
  A34: 'L3',
  B34: '',
  C34: '',
  D34: '',
  E34: (payload) => payload.l3.sides.l,
  F34: (payload) => payload.l3.sides.r,
  G34: (payload) => payload.l3.sides.b,
  H34: '',
  I34: (payload) => payload.l3.of.sublux,
  J34: (payload) => payload.l3.of.muscleSpasm,
  K34: (payload) => payload.l3.of.triggerPoints,
  L34: (payload) => payload.l3.of.tenderness,
  M34: (payload) => payload.l3.of.numbness,
  N34: (payload) => payload.l3.of.edema,
  O34: (payload) => payload.l3.of.swelling,
  P34: (payload) => payload.l3.of.reducedMotion,
  Q34: '',
  R34: (payload) => payload.l3.physio.positioning,
  S34: (payload) => payload.l3.physio.coldPacks,
  T34: (payload) => payload.l3.physio.hotPacks,
  U34: '',
  V34: (payload) => payload.l3.physio.electStim,
  W34: '',
  X34: (payload) => payload.l3.physio.traction,
  Y34: (payload) => payload.l3.physio.massage,
  Z34: '',
  AA34: (payload) => payload.l3.treatment.positioning,
  AB34: (payload) => payload.l3.treatment.techniques,
  AC34: (payload) => payload.l3.treatment.manipulation,
  A35: 'L4',
  B35: 'Lower L',
  C35: '',
  D35: '',
  E35: (payload) => payload.l4.sides.l,
  F35: (payload) => payload.l4.sides.r,
  G35: (payload) => payload.l4.sides.b,
  H35: '',
  I35: (payload) => payload.l4.of.sublux,
  J35: (payload) => payload.l4.of.muscleSpasm,
  K35: (payload) => payload.l4.of.triggerPoints,
  L35: (payload) => payload.l4.of.tenderness,
  M35: (payload) => payload.l4.of.numbness,
  N35: (payload) => payload.l4.of.edema,
  O35: (payload) => payload.l4.of.swelling,
  P35: (payload) => payload.l4.of.reducedMotion,
  Q35: '',
  R35: (payload) => payload.l4.physio.positioning,
  S35: (payload) => payload.l4.physio.coldPacks,
  T35: (payload) => payload.l4.physio.hotPacks,
  U35: '',
  V35: (payload) => payload.l4.physio.electStim,
  W35: '',
  X35: (payload) => payload.l4.physio.traction,
  Y35: (payload) => payload.l4.physio.massage,
  Z35: '',
  AA35: (payload) => payload.l4.treatment.positioning,
  AB35: (payload) => payload.l4.treatment.techniques,
  AC35: (payload) => payload.l4.treatment.manipulation,
  A36: 'L5',
  B36: '',
  C36: '',
  D36: '',
  E36: (payload) => payload.l5.sides.l,
  F36: (payload) => payload.l5.sides.r,
  G36: (payload) => payload.l5.sides.b,
  H36: '',
  I36: (payload) => payload.l5.of.sublux,
  J36: (payload) => payload.l5.of.muscleSpasm,
  K36: (payload) => payload.l5.of.triggerPoints,
  L36: (payload) => payload.l5.of.tenderness,
  M36: (payload) => payload.l5.of.numbness,
  N36: (payload) => payload.l5.of.edema,
  O36: (payload) => payload.l5.of.swelling,
  P36: (payload) => payload.l5.of.reducedMotion,
  Q36: '',
  R36: (payload) => payload.l5.physio.positioning,
  S36: (payload) => payload.l5.physio.coldPacks,
  T36: (payload) => payload.l5.physio.hotPacks,
  U36: '',
  V36: (payload) => payload.l5.physio.electStim,
  W36: '',
  X36: (payload) => payload.l5.physio.traction,
  Y36: (payload) => payload.l5.physio.massage,
  Z36: '',
  AA36: (payload) => payload.l5.treatment.positioning,
  AB36: (payload) => payload.l5.treatment.techniques,
  AC36: (payload) => payload.l5.treatment.manipulation,
  A37: '',
  B37: '',
  C37: '',
  D37: '',
  E37: '',
  F37: '',
  G37: '',
  H37: '',
  I37: '',
  J37: '',
  K37: '',
  L37: '',
  M37: '',
  N37: '',
  O37: '',
  P37: '',
  Q37: '',
  R37: '',
  S37: '',
  T37: '',
  U37: '',
  V37: '',
  W37: '',
  X37: '',
  Y37: '',
  Z37: '',
  AA37: '',
  AB37: '',
  AC37: '',
  A38: 'S1',
  B38: 'Upper Sac',
  C38: 'Full Sac-Region',
  D38: '',
  E38: (payload) => payload.s1.sides.l,
  F38: (payload) => payload.s1.sides.r,
  G38: (payload) => payload.s1.sides.b,
  H38: '',
  I38: (payload) => payload.s1.of.sublux,
  J38: (payload) => payload.s1.of.muscleSpasm,
  K38: (payload) => payload.s1.of.triggerPoints,
  L38: (payload) => payload.s1.of.tenderness,
  M38: (payload) => payload.s1.of.numbness,
  N38: (payload) => payload.s1.of.edema,
  O38: (payload) => payload.s1.of.swelling,
  P38: (payload) => payload.s1.of.reducedMotion,
  Q38: '',
  R38: (payload) => payload.s1.physio.positioning,
  S38: (payload) => payload.s1.physio.coldPacks,
  T38: (payload) => payload.s1.physio.hotPacks,
  U38: '',
  V38: (payload) => payload.s1.physio.electStim,
  W38: '',
  X38: (payload) => payload.s1.physio.traction,
  Y38: (payload) => payload.s1.physio.massage,
  Z38: '',
  AA38: (payload) => payload.s1.treatment.positioning,
  AB38: (payload) => payload.s1.treatment.techniques,
  AC38: (payload) => payload.s1.treatment.manipulation,
  A39: 'S2',
  B39: '',
  C39: '',
  D39: '',
  E39: (payload) => payload.s2.sides.l,
  F39: (payload) => payload.s2.sides.r,
  G39: (payload) => payload.s2.sides.b,
  H39: '',
  I39: (payload) => payload.s2.of.sublux,
  J39: (payload) => payload.s2.of.muscleSpasm,
  K39: (payload) => payload.s2.of.triggerPoints,
  L39: (payload) => payload.s2.of.tenderness,
  M39: (payload) => payload.s2.of.numbness,
  N39: (payload) => payload.s2.of.edema,
  O39: (payload) => payload.s2.of.swelling,
  P39: (payload) => payload.s2.of.reducedMotion,
  Q39: '',
  R39: (payload) => payload.s2.physio.positioning,
  S39: (payload) => payload.s2.physio.coldPacks,
  T39: (payload) => payload.s2.physio.hotPacks,
  U39: '',
  V39: (payload) => payload.s2.physio.electStim,
  W39: '',
  X39: (payload) => payload.s2.physio.traction,
  Y39: (payload) => payload.s2.physio.massage,
  Z39: '',
  AA39: (payload) => payload.s2.treatment.positioning,
  AB39: (payload) => payload.s2.treatment.techniques,
  AC39: (payload) => payload.s2.treatment.manipulation,
  A40: 'S3',
  B40: '',
  C40: '',
  D40: '',
  E40: (payload) => payload.s3.sides.l,
  F40: (payload) => payload.s3.sides.r,
  G40: (payload) => payload.s3.sides.b,
  H40: '',
  I40: (payload) => payload.s3.of.sublux,
  J40: (payload) => payload.s3.of.muscleSpasm,
  K40: (payload) => payload.s3.of.triggerPoints,
  L40: (payload) => payload.s3.of.tenderness,
  M40: (payload) => payload.s3.of.numbness,
  N40: (payload) => payload.s3.of.edema,
  O40: (payload) => payload.s3.of.swelling,
  P40: (payload) => payload.s3.of.reducedMotion,
  Q40: '',
  R40: (payload) => payload.s3.physio.positioning,
  S40: (payload) => payload.s3.physio.coldPacks,
  T40: (payload) => payload.s3.physio.hotPacks,
  U40: '',
  V40: (payload) => payload.s3.physio.electStim,
  W40: '',
  X40: (payload) => payload.s3.physio.traction,
  Y40: (payload) => payload.s3.physio.massage,
  Z40: '',
  AA40: (payload) => payload.s3.treatment.positioning,
  AB40: (payload) => payload.s3.treatment.techniques,
  AC40: (payload) => payload.s3.treatment.manipulation,
  A41: 'S4',
  B41: 'Lower Sac',
  C41: '',
  D41: '',
  E41: (payload) => payload.s4.sides.l,
  F41: (payload) => payload.s4.sides.r,
  G41: (payload) => payload.s4.sides.b,
  H41: '',
  I41: (payload) => payload.s4.of.sublux,
  J41: (payload) => payload.s4.of.muscleSpasm,
  K41: (payload) => payload.s4.of.triggerPoints,
  L41: (payload) => payload.s4.of.tenderness,
  M41: (payload) => payload.s4.of.numbness,
  N41: (payload) => payload.s4.of.edema,
  O41: (payload) => payload.s4.of.swelling,
  P41: (payload) => payload.s4.of.reducedMotion,
  Q41: '',
  R41: (payload) => payload.s4.physio.positioning,
  S41: (payload) => payload.s4.physio.coldPacks,
  T41: (payload) => payload.s4.physio.hotPacks,
  U41: '',
  V41: (payload) => payload.s4.physio.electStim,
  W41: '',
  X41: (payload) => payload.s4.physio.traction,
  Y41: (payload) => payload.s4.physio.massage,
  Z41: '',
  AA41: (payload) => payload.s4.treatment.positioning,
  AB41: (payload) => payload.s4.treatment.techniques,
  AC41: (payload) => payload.s4.treatment.manipulation,
  A42: 'S5',
  B42: '',
  C42: '',
  D42: '',
  E42: (payload) => payload.s5.sides.l,
  F42: (payload) => payload.s5.sides.r,
  G42: (payload) => payload.s5.sides.b,
  H42: '',
  I42: (payload) => payload.s5.of.sublux,
  J42: (payload) => payload.s5.of.muscleSpasm,
  K42: (payload) => payload.s5.of.triggerPoints,
  L42: (payload) => payload.s5.of.tenderness,
  M42: (payload) => payload.s5.of.numbness,
  N42: (payload) => payload.s5.of.edema,
  O42: (payload) => payload.s5.of.swelling,
  P42: (payload) => payload.s5.of.reducedMotion,
  Q42: '',
  R42: (payload) => payload.s5.physio.positioning,
  S42: (payload) => payload.s5.physio.coldPacks,
  T42: (payload) => payload.s5.physio.hotPacks,
  U42: '',
  V42: (payload) => payload.s5.physio.electStim,
  W42: '',
  X42: (payload) => payload.s5.physio.traction,
  Y42: (payload) => payload.s5.physio.massage,
  Z42: '',
  AA42: (payload) => payload.s5.treatment.positioning,
  AB42: (payload) => payload.s5.treatment.techniques,
  AC42: (payload) => payload.s5.treatment.manipulation,
  A43: '',
  B43: '',
  C43: '',
  D43: '',
  E43: '',
  F43: '',
  G43: '',
  H43: '',
  I43: '',
  J43: '',
  K43: '',
  L43: '',
  M43: '',
  N43: '',
  O43: '',
  P43: '',
  Q43: '',
  R43: '',
  S43: '',
  T43: '',
  U43: '',
  V43: '',
  W43: '',
  X43: '',
  Y43: '',
  Z43: '',
  AA43: '',
  AB43: '',
  AC43: '',
  A44: '',
  B44: '',
  C44: '',
  D44: '',
  E44: '',
  F44: '',
  G44: '',
  H44: '',
  I44: '',
  J44: '',
  K44: '',
  L44: '',
  M44: '',
  N44: '',
  O44: '',
  P44: '',
  Q44: '',
  R44: '',
  S44: '',
  T44: '',
  U44: '',
  V44: '',
  W44: '',
  X44: '',
  Y44: '',
  Z44: '',
  AA44: '',
  AB44: '',
  AC44: '',
  A45: 'EXTREMITIES',
  B45: '',
  C45: '',
  D45: '',
  E45: 'SIDES',
  F45: '',
  G45: '',
  H45: '',
  I45: 'OBJECTIVE FINDINGS',
  J45: '',
  K45: '',
  L45: '',
  M45: '',
  N45: '',
  O45: '',
  P45: '',
  Q45: '',
  R45: 'PHYSIOTHERAPIES',
  S45: '',
  T45: '',
  U45: '',
  V45: '',
  W45: '',
  X45: '',
  Y45: '',
  Z45: '',
  AA45: 'TREATMENT',
  AB45: '',
  AC45: '',
  A46: 'LEVELS',
  B46: '',
  C46: '',
  D46: '',
  E46: 'L',
  F46: 'R',
  G46: 'B',
  H46: '',
  I46: 'Subluxation',
  J46: 'Muscle Spasm',
  K46: 'Trigger Points',
  L46: 'Tenderness',
  M46: 'Numbness',
  N46: 'Edema',
  O46: 'Swelling',
  P46: 'Reduced Motion',
  Q46: '',
  R46: 'Positioning',
  S46: 'Cold Packs',
  T46: 'Hot Packs',
  U46: '',
  V46: 'Electrical Stimulation',
  W46: '',
  X46: 'Traction',
  Y46: 'Massage',
  Z46: '',
  AA46: 'Positioning',
  AB46: 'Techniques',
  AC46: 'Manipulation',
  A47: '',
  B47: '',
  C47: '',
  D47: '',
  E47: '',
  F47: '',
  G47: '',
  H47: '',
  I47: '',
  J47: '',
  K47: '',
  L47: '',
  M47: '',
  N47: '',
  O47: '',
  P47: '',
  Q47: '',
  R47: '',
  S47: '',
  T47: '',
  U47: '',
  V47: '',
  W47: '',
  X47: '',
  Y47: '',
  Z47: '',
  AA47: '',
  AB47: '',
  AC47: '',
  A48: 'Shoulder',
  B48: '',
  C48: '',
  D48: '',
  E48: (payload) => payload.shoulder.sides.l || '',
  F48: (payload) => payload.shoulder.sides.r || '',
  G48: (payload) => payload.shoulder.sides.b || '',
  H48: '',
  I48: (payload) => payload.shoulder.of.sublux || '',
  J48: (payload) => payload.shoulder.of.muscleSpasm || '',
  K48: (payload) => payload.shoulder.of.triggerPoints || '',
  L48: (payload) => payload.shoulder.of.tenderness || '',
  M48: (payload) => payload.shoulder.of.numbness || '',
  N48: (payload) => payload.shoulder.of.edema || '',
  O48: (payload) => payload.shoulder.of.swelling || '',
  P48: (payload) => payload.shoulder.of.reducedMotion || '',
  Q48: '',
  R48: (payload) => payload.shoulder.physio.positioning || '',
  S48: (payload) => payload.shoulder.physio.coldPacks || '',
  T48: (payload) => payload.shoulder.physio.hotPacks || '',
  U48: '',
  V48: (payload) => payload.shoulder.physio.electStim || '',
  W48: '',
  X48: (payload) => payload.shoulder.physio.traction || '',
  Y48: (payload) => payload.shoulder.physio.massage || '',
  Z48: '',
  AA48: (payload) => payload.shoulder.treatment.positioning || '',
  AB48: (payload) => payload.shoulder.treatment.techniques || '',
  AC48: (payload) => payload.shoulder.treatment.manipulation || '',
  A49: 'Arm',
  B49: '',
  C49: '',
  D49: '',
  E49: (payload) => payload.arm.sides.l || '',
  F49: (payload) => payload.arm.sides.r || '',
  G49: (payload) => payload.arm.sides.b || '',
  H49: '',
  I49: (payload) => payload.arm.of.sublux || '',
  J49: (payload) => payload.arm.of.muscleSpasm || '',
  K49: (payload) => payload.arm.of.triggerPoints || '',
  L49: (payload) => payload.arm.of.tenderness || '',
  M49: (payload) => payload.arm.of.numbness || '',
  N49: (payload) => payload.arm.of.edema || '',
  O49: (payload) => payload.arm.of.swelling || '',
  P49: (payload) => payload.arm.of.reducedMotion || '',
  Q49: '',
  R49: (payload) => payload.arm.physio.positioning || '',
  S49: (payload) => payload.arm.physio.coldPacks || '',
  T49: (payload) => payload.arm.physio.hotPacks || '',
  U49: '',
  V49: (payload) => payload.arm.physio.electStim || '',
  W49: '',
  X49: (payload) => payload.arm.physio.traction || '',
  Y49: (payload) => payload.arm.physio.massage || '',
  Z49: '',
  AA49: (payload) => payload.arm.treatment.positioning || '',
  AB49: (payload) => payload.arm.treatment.techniques || '',
  AC49: (payload) => payload.arm.treatment.manipulation || '',
  A50: 'Bicep',
  B50: '',
  C50: '',
  D50: '',
  E50: (payload) => payload.bicep.sides.l || '',
  F50: (payload) => payload.bicep.sides.r || '',
  G50: (payload) => payload.bicep.sides.b || '',
  H50: '',
  I50: (payload) => payload.bicep.of.sublux || '',
  J50: (payload) => payload.bicep.of.muscleSpasm || '',
  K50: (payload) => payload.bicep.of.triggerPoints || '',
  L50: (payload) => payload.bicep.of.tenderness || '',
  M50: (payload) => payload.bicep.of.numbness || '',
  N50: (payload) => payload.bicep.of.edema || '',
  O50: (payload) => payload.bicep.of.swelling || '',
  P50: (payload) => payload.bicep.of.reducedMotion || '',
  Q50: '',
  R50: (payload) => payload.bicep.physio.positioning || '',
  S50: (payload) => payload.bicep.physio.coldPacks || '',
  T50: (payload) => payload.bicep.physio.hotPacks || '',
  U50: '',
  V50: (payload) => payload.bicep.physio.electStim || '',
  W50: '',
  X50: (payload) => payload.bicep.physio.traction || '',
  Y50: (payload) => payload.bicep.physio.massage || '',
  Z50: '',
  AA50: (payload) => payload.bicep.treatment.positioning || '',
  AB50: (payload) => payload.bicep.treatment.techniques || '',
  AC50: (payload) => payload.bicep.treatment.manipulation || '',
  A51: 'Tricep',
  B51: '',
  C51: '',
  D51: '',
  E51: (payload) => payload.tricep.sides.l || '',
  F51: (payload) => payload.tricep.sides.r || '',
  G51: (payload) => payload.tricep.sides.b || '',
  H51: '',
  I51: (payload) => payload.tricep.of.sublux || '',
  J51: (payload) => payload.tricep.of.muscleSpasm || '',
  K51: (payload) => payload.tricep.of.triggerPoints || '',
  L51: (payload) => payload.tricep.of.tenderness || '',
  M51: (payload) => payload.tricep.of.numbness || '',
  N51: (payload) => payload.tricep.of.edema || '',
  O51: (payload) => payload.tricep.of.swelling || '',
  P51: (payload) => payload.tricep.of.reducedMotion || '',
  Q51: '',
  R51: (payload) => payload.tricep.physio.positioning || '',
  S51: (payload) => payload.tricep.physio.coldPacks || '',
  T51: (payload) => payload.tricep.physio.hotPacks || '',
  U51: '',
  V51: (payload) => payload.tricep.physio.electStim || '',
  W51: '',
  X51: (payload) => payload.tricep.physio.traction || '',
  Y51: (payload) => payload.tricep.physio.massage || '',
  Z51: '',
  AA51: (payload) => payload.tricep.treatment.positioning || '',
  AB51: (payload) => payload.tricep.treatment.techniques || '',
  AC51: (payload) => payload.tricep.treatment.manipulation || '',
  A52: 'Elbow',
  B52: '',
  C52: '',
  D52: '',
  E52: (payload) => payload.elbow.sides.l || '',
  F52: (payload) => payload.elbow.sides.r || '',
  G52: (payload) => payload.elbow.sides.b || '',
  H52: '',
  I52: (payload) => payload.elbow.of.sublux || '',
  J52: (payload) => payload.elbow.of.muscleSpasm || '',
  K52: (payload) => payload.elbow.of.triggerPoints || '',
  L52: (payload) => payload.elbow.of.tenderness || '',
  M52: (payload) => payload.elbow.of.numbness || '',
  N52: (payload) => payload.elbow.of.edema || '',
  O52: (payload) => payload.elbow.of.swelling || '',
  P52: (payload) => payload.elbow.of.reducedMotion || '',
  Q52: '',
  R52: (payload) => payload.elbow.physio.positioning || '',
  S52: (payload) => payload.elbow.physio.coldPacks || '',
  T52: (payload) => payload.elbow.physio.hotPacks || '',
  U52: '',
  V52: (payload) => payload.elbow.physio.electStim || '',
  W52: '',
  X52: (payload) => payload.elbow.physio.traction || '',
  Y52: (payload) => payload.elbow.physio.massage || '',
  Z52: '',
  AA52: (payload) => payload.elbow.treatment.positioning || '',
  AB52: (payload) => payload.elbow.treatment.techniques || '',
  AC52: (payload) => payload.elbow.treatment.manipulation || '',
  A53: 'Wrist',
  B53: '',
  C53: '',
  D53: '',
  E53: (payload) => payload.wrist.sides.l || '',
  F53: (payload) => payload.wrist.sides.r || '',
  G53: (payload) => payload.wrist.sides.b || '',
  H53: '',
  I53: (payload) => payload.wrist.of.sublux || '',
  J53: (payload) => payload.wrist.of.muscleSpasm || '',
  K53: (payload) => payload.wrist.of.triggerPoints || '',
  L53: (payload) => payload.wrist.of.tenderness || '',
  M53: (payload) => payload.wrist.of.numbness || '',
  N53: (payload) => payload.wrist.of.edema || '',
  O53: (payload) => payload.wrist.of.swelling || '',
  P53: (payload) => payload.wrist.of.reducedMotion || '',
  Q53: '',
  R53: (payload) => payload.wrist.physio.positioning || '',
  S53: (payload) => payload.wrist.physio.coldPacks || '',
  T53: (payload) => payload.wrist.physio.hotPacks || '',
  U53: '',
  V53: (payload) => payload.wrist.physio.electStim || '',
  W53: '',
  X53: (payload) => payload.wrist.physio.traction || '',
  Y53: (payload) => payload.wrist.physio.massage || '',
  Z53: '',
  AA53: (payload) => payload.wrist.treatment.positioning || '',
  AB53: (payload) => payload.wrist.treatment.techniques || '',
  AC53: (payload) => payload.wrist.treatment.manipulation || '',
  A54: 'Hand',
  B54: '',
  C54: '',
  D54: '',
  E54: (payload) => payload.hand.sides.l || '',
  F54: (payload) => payload.hand.sides.r || '',
  G54: (payload) => payload.hand.sides.b || '',
  H54: '',
  I54: (payload) => payload.hand.of.sublux || '',
  J54: (payload) => payload.hand.of.muscleSpasm || '',
  K54: (payload) => payload.hand.of.triggerPoints || '',
  L54: (payload) => payload.hand.of.tenderness || '',
  M54: (payload) => payload.hand.of.numbness || '',
  N54: (payload) => payload.hand.of.edema || '',
  O54: (payload) => payload.hand.of.swelling || '',
  P54: (payload) => payload.hand.of.reducedMotion || '',
  Q54: '',
  R54: (payload) => payload.hand.physio.positioning || '',
  S54: (payload) => payload.hand.physio.coldPacks || '',
  T54: (payload) => payload.hand.physio.hotPacks || '',
  U54: '',
  V54: (payload) => payload.hand.physio.electStim || '',
  W54: '',
  X54: (payload) => payload.hand.physio.traction || '',
  Y54: (payload) => payload.hand.physio.massage || '',
  Z54: '',
  AA54: (payload) => payload.hand.treatment.positioning || '',
  AB54: (payload) => payload.hand.treatment.techniques || '',
  AC54: (payload) => payload.hand.treatment.manipulation || '',

  A55: 'Hip',
  B55: '',
  C55: '',
  D55: '',
  E55: (payload) => payload.hip.sides.l || '',
  F55: (payload) => payload.hip.sides.r || '',
  G55: (payload) => payload.hip.sides.b || '',
  H55: '',
  I55: (payload) => payload.hip.of.sublux || '',
  J55: (payload) => payload.hip.of.muscleSpasm || '',
  K55: (payload) => payload.hip.of.triggerPoints || '',
  L55: (payload) => payload.hip.of.tenderness || '',
  M55: (payload) => payload.hip.of.numbness || '',
  N55: (payload) => payload.hip.of.edema || '',
  O55: (payload) => payload.hip.of.swelling || '',
  P55: (payload) => payload.hip.of.reducedMotion || '',
  Q55: '',
  R55: (payload) => payload.hip.physio.positioning || '',
  S55: (payload) => payload.hip.physio.coldPacks || '',
  T55: (payload) => payload.hip.physio.hotPacks || '',
  U55: '',
  V55: (payload) => payload.hip.physio.electStim || '',
  W55: '',
  X55: (payload) => payload.hip.physio.traction || '',
  Y55: (payload) => payload.hip.physio.massage || '',
  Z55: '',
  AA55: (payload) => payload.hip.treatment.positioning || '',
  AB55: (payload) => payload.hip.treatment.techniques || '',
  AC55: (payload) => payload.hip.treatment.manipulation || '',

  A56: 'Thigh',
  B56: '',
  C56: '',
  D56: '',
  E56: (payload) => payload.thigh.sides.l || '',
  F56: (payload) => payload.thigh.sides.r || '',
  G56: (payload) => payload.thigh.sides.b || '',
  H56: '',
  I56: (payload) => payload.thigh.of.sublux || '',
  J56: (payload) => payload.thigh.of.muscleSpasm || '',
  K56: (payload) => payload.thigh.of.triggerPoints || '',
  L56: (payload) => payload.thigh.of.tenderness || '',
  M56: (payload) => payload.thigh.of.numbness || '',
  N56: (payload) => payload.thigh.of.edema || '',
  O56: (payload) => payload.thigh.of.swelling || '',
  P56: (payload) => payload.thigh.of.reducedMotion || '',
  Q56: '',
  R56: (payload) => payload.thigh.physio.positioning || '',
  S56: (payload) => payload.thigh.physio.coldPacks || '',
  T56: (payload) => payload.thigh.physio.hotPacks || '',
  U56: '',
  V56: (payload) => payload.thigh.physio.electStim || '',
  W56: '',
  X56: (payload) => payload.thigh.physio.traction || '',
  Y56: (payload) => payload.thigh.physio.massage || '',
  Z56: '',
  AA56: (payload) => payload.thigh.treatment.positioning || '',
  AB56: (payload) => payload.thigh.treatment.techniques || '',
  AC56: (payload) => payload.thigh.treatment.manipulation || '',

  A57: 'Leg',
  B57: '',
  C57: '',
  D57: '',
  E57: (payload) => payload.leg.sides.l || '',
  F57: (payload) => payload.leg.sides.r || '',
  G57: (payload) => payload.leg.sides.b || '',
  H57: '',
  I57: (payload) => payload.leg.of.sublux || '',
  J57: (payload) => payload.leg.of.muscleSpasm || '',
  K57: (payload) => payload.leg.of.triggerPoints || '',
  L57: (payload) => payload.leg.of.tenderness || '',
  M57: (payload) => payload.leg.of.numbness || '',
  N57: (payload) => payload.leg.of.edema || '',
  O57: (payload) => payload.leg.of.swelling || '',
  P57: (payload) => payload.leg.of.reducedMotion || '',
  Q57: '',
  R57: (payload) => payload.leg.physio.positioning || '',
  S57: (payload) => payload.leg.physio.coldPacks || '',
  T57: (payload) => payload.leg.physio.hotPacks || '',
  U57: '',
  V57: (payload) => payload.leg.physio.electStim || '',
  W57: '',
  X57: (payload) => payload.leg.physio.traction || '',
  Y57: (payload) => payload.leg.physio.massage || '',
  Z57: '',
  AA57: (payload) => payload.leg.treatment.positioning || '',
  AB57: (payload) => payload.leg.treatment.techniques || '',
  AC57: (payload) => payload.leg.treatment.manipulation || '',

  A58: 'Knee',
  B58: '',
  C58: '',
  D58: '',
  E58: (payload) => payload.knee.sides.l || '',
  F58: (payload) => payload.knee.sides.r || '',
  G58: (payload) => payload.knee.sides.b || '',
  H58: '',
  I58: (payload) => payload.knee.of.sublux || '',
  J58: (payload) => payload.knee.of.muscleSpasm || '',
  K58: (payload) => payload.knee.of.triggerPoints || '',
  L58: (payload) => payload.knee.of.tenderness || '',
  M58: (payload) => payload.knee.of.numbness || '',
  N58: (payload) => payload.knee.of.edema || '',
  O58: (payload) => payload.knee.of.swelling || '',
  P58: (payload) => payload.knee.of.reducedMotion || '',
  Q58: '',
  R58: (payload) => payload.knee.physio.positioning || '',
  S58: (payload) => payload.knee.physio.coldPacks || '',
  T58: (payload) => payload.knee.physio.hotPacks || '',
  U58: '',
  V58: (payload) => payload.knee.physio.electStim || '',
  W58: '',
  X58: (payload) => payload.knee.physio.traction || '',
  Y58: (payload) => payload.knee.physio.massage || '',
  Z58: '',
  AA58: (payload) => payload.knee.treatment.positioning || '',
  AB58: (payload) => payload.knee.treatment.techniques || '',
  AC58: (payload) => payload.knee.treatment.manipulation || '',

  // A59: "Knee Cap",
  // B59:"",
  // C59:"",
  // D59:"",
  // E59: (payload) => payload.kneeCap.sides.l || "",
  // F59: (payload) => payload.kneeCap.sides.r || "",
  // G59: (payload) => payload.kneeCap.sides.b || "",
  // H59:"",
  // I59: (payload) => payload.kneeCap.of.sublux || "",
  // J59: (payload) => payload.kneeCap.of.muscleSpasm || "",
  // K59: (payload) => payload.kneeCap.of.triggerPoints || "",
  // L59: (payload) => payload.kneeCap.of.tenderness || "",
  // M59: (payload) => payload.kneeCap.of.numbness || "",
  // N59: (payload) => payload.kneeCap.of.edema || "",
  // O59: (payload) => payload.kneeCap.of.swelling || "",
  // P59: (payload) => payload.kneeCap.of.reducedMotion || "",
  // Q59:"",
  // R59: (payload) => payload.kneeCap.physio.positioning || "",
  // S59: (payload) => payload.kneeCap.physio.coldPacks || "",
  // T59: (payload) => payload.kneeCap.physio.hotPacks || "",
  // U59:"",
  // V59: (payload) => payload.kneeCap.physio.electStim || "",
  // W59:"",
  // X59: (payload) => payload.kneeCap.physio.traction || "",
  // Y59: (payload) => payload.kneeCap.physio.massage || "",
  // Z59:"",
  // AA59: (payload) => payload.kneeCap.treatment.positioning || "",
  // AB59: (payload) => payload.kneeCap.treatment.techniques || "",
  // AC59: (payload) => payload.kneeCap.treatment.manipulation || "",
  A60: 'Calf',
  B60: '',
  C60: '',
  D60: '',
  E60: (payload) => payload.calf.sides.l || '',
  F60: (payload) => payload.calf.sides.r || '',
  G60: (payload) => payload.calf.sides.b || '',
  H60: '',
  I60: (payload) => payload.calf.of.sublux || '',
  J60: (payload) => payload.calf.of.muscleSpasm || '',
  K60: (payload) => payload.calf.of.triggerPoints || '',
  L60: (payload) => payload.calf.of.tenderness || '',
  M60: (payload) => payload.calf.of.numbness || '',
  N60: (payload) => payload.calf.of.edema || '',
  O60: (payload) => payload.calf.of.swelling || '',
  P60: (payload) => payload.calf.of.reducedMotion || '',
  Q60: '',
  R60: (payload) => payload.calf.physio.positioning || '',
  S60: (payload) => payload.calf.physio.coldPacks || '',
  T60: (payload) => payload.calf.physio.hotPacks || '',
  U60: '',
  V60: (payload) => payload.calf.physio.electStim || '',
  W60: '',
  X60: (payload) => payload.calf.physio.traction || '',
  Y60: (payload) => payload.calf.physio.massage || '',
  Z60: '',
  AA60: (payload) => payload.calf.treatment.positioning || '',
  AB60: (payload) => payload.calf.treatment.techniques || '',
  AC60: (payload) => payload.calf.treatment.manipulation || '',

  A61: 'Ankle',
  B61: '',
  C61: '',
  D61: '',
  E61: (payload) => payload.ankle.sides.l || '',
  F61: (payload) => payload.ankle.sides.r || '',
  G61: (payload) => payload.ankle.sides.b || '',
  H61: '',
  I61: (payload) => payload.ankle.of.sublux || '',
  J61: (payload) => payload.ankle.of.muscleSpasm || '',
  K61: (payload) => payload.ankle.of.triggerPoints || '',
  L61: (payload) => payload.ankle.of.tenderness || '',
  M61: (payload) => payload.ankle.of.numbness || '',
  N61: (payload) => payload.ankle.of.edema || '',
  O61: (payload) => payload.ankle.of.swelling || '',
  P61: (payload) => payload.ankle.of.reducedMotion || '',
  Q61: '',
  R61: (payload) => payload.ankle.physio.positioning || '',
  S61: (payload) => payload.ankle.physio.coldPacks || '',
  T61: (payload) => payload.ankle.physio.hotPacks || '',
  U61: '',
  V61: (payload) => payload.ankle.physio.electStim || '',
  W61: '',
  X61: (payload) => payload.ankle.physio.traction || '',
  Y61: (payload) => payload.ankle.physio.massage || '',
  Z61: '',
  AA61: (payload) => payload.ankle.treatment.positioning || '',
  AB61: (payload) => payload.ankle.treatment.techniques || '',
  AC61: (payload) => payload.ankle.treatment.manipulation || '',

  A62: 'Foot',
  B62: '',
  C62: '',
  D62: '',
  E62: (payload) => payload.foot.sides.l || '',
  F62: (payload) => payload.foot.sides.r || '',
  G62: (payload) => payload.foot.sides.b || '',
  H62: '',
  I62: (payload) => payload.foot.of.sublux || '',
  J62: (payload) => payload.foot.of.muscleSpasm || '',
  K62: (payload) => payload.foot.of.triggerPoints || '',
  L62: (payload) => payload.foot.of.tenderness || '',
  M62: (payload) => payload.foot.of.numbness || '',
  N62: (payload) => payload.foot.of.edema || '',
  O62: (payload) => payload.foot.of.swelling || '',
  P62: (payload) => payload.foot.of.reducedMotion || '',
  Q62: '',
  R62: (payload) => payload.foot.physio.positioning || '',
  S62: (payload) => payload.foot.physio.coldPacks || '',
  T62: (payload) => payload.foot.physio.hotPacks || '',
  U62: '',
  V62: (payload) => payload.foot.physio.electStim || '',
  W62: '',
  X62: (payload) => payload.foot.physio.traction || '',
  Y62: (payload) => payload.foot.physio.massage || '',
  Z62: '',
  AA62: (payload) => payload.foot.treatment.positioning || '',
  AB62: (payload) => payload.foot.treatment.techniques || '',
  AC62: (payload) => payload.foot.treatment.manipulation || '',
};

// export const mergedCells = [
//     ["A7", "C7"],
//     ["E7", "G7"],
//     ["I7", "P7"],
//     ["R7", "Y7"],
//     ["AA7", "AC7"],
//     ["B8", "C8"],
//   ];

// export const mergedCells = [
//     ['A7', 'C7'],
//     ['E7', 'G7'],
//     ['I7', 'P7'],
//     ['R7', 'Y7'],
//     ['AA7', 'AC7'],
//     ['B8', 'C8'],
//   ];
