export const spinalEntries = [
  {
    spinalLevel: 'occ_c1',
    side: null,
    sublux: false,
    muscleSpasm: false,
    triggerPoints: false,
    tenderness: false,
    numbness: false,
    edema: false,
    swelling: false,
    reducedMotion: false,
    coldPack: false,
    hotPack: false,
    electStim: false,
    traction: false,
    massage: false,
    manipulation: false,
  },
  {
    spinalLevel: 'c1_c2',
    side: null,
    sublux: false,
    muscleSpasm: false,
    triggerPoints: false,
    tenderness: false,
    numbness: false,
    edema: false,
    swelling: false,
    reducedMotion: false,
    coldPack: false,
    hotPack: false,
    electStim: false,
    traction: false,
    massage: false,
    manipulation: false,
  },
  {
    spinalLevel: 'c2_c3',
    side: null,
    sublux: false,
    muscleSpasm: false,
    triggerPoints: false,
    tenderness: false,
    numbness: false,
    edema: false,
    swelling: false,
    reducedMotion: false,
    coldPack: false,
    hotPack: false,
    electStim: false,
    traction: false,
    massage: false,
    manipulation: false,
  },
  {
    spinalLevel: 'c3_c4',
    side: null,
    sublux: false,
    muscleSpasm: false,
    triggerPoints: false,
    tenderness: false,
    numbness: false,
    edema: false,
    swelling: false,
    reducedMotion: false,
    coldPack: false,
    hotPack: false,
    electStim: false,
    traction: false,
    massage: false,
    manipulation: false,
  },
  {
    spinalLevel: 'c5_c6',
    side: null,
    sublux: false,
    muscleSpasm: false,
    triggerPoints: false,
    tenderness: false,
    numbness: false,
    edema: false,
    swelling: false,
    reducedMotion: false,
    coldPack: false,
    hotPack: false,
    electStim: false,
    traction: false,
    massage: false,
    manipulation: false,
  },
  {
    spinalLevel: 'c6_c7',
    side: null,
    sublux: false,
    muscleSpasm: false,
    triggerPoints: false,
    tenderness: false,
    numbness: false,
    edema: false,
    swelling: false,
    reducedMotion: false,
    coldPack: false,
    hotPack: false,
    electStim: false,
    traction: false,
    massage: false,
    manipulation: false,
  },
  {
    spinalLevel: 'c7_t1',
    side: null,
    sublux: false,
    muscleSpasm: false,
    triggerPoints: false,
    tenderness: false,
    numbness: false,
    edema: false,
    swelling: false,
    reducedMotion: false,
    coldPack: false,
    hotPack: false,
    electStim: false,
    traction: false,
    massage: false,
    manipulation: false,
  },
  {
    spinalLevel: 't1_t2',
    side: null,
    sublux: false,
    muscleSpasm: false,
    triggerPoints: false,
    tenderness: false,
    numbness: false,
    edema: false,
    swelling: false,
    reducedMotion: false,
    coldPack: false,
    hotPack: false,
    electStim: false,
    traction: false,
    massage: false,
    manipulation: false,
  },
  {
    spinalLevel: 't2_t3',
    side: null,
    sublux: false,
    muscleSpasm: false,
    triggerPoints: false,
    tenderness: false,
    numbness: false,
    edema: false,
    swelling: false,
    reducedMotion: false,
    coldPack: false,
    hotPack: false,
    electStim: false,
    traction: false,
    massage: false,
    manipulation: false,
  },
  {
    spinalLevel: 't3_t4',
    side: null,
    sublux: false,
    muscleSpasm: false,
    triggerPoints: false,
    tenderness: false,
    numbness: false,
    edema: false,
    swelling: false,
    reducedMotion: false,
    coldPack: false,
    hotPack: false,
    electStim: false,
    traction: false,
    massage: false,
    manipulation: false,
  },
  {
    spinalLevel: 't4_t5',
    side: null,
    sublux: false,
    muscleSpasm: false,
    triggerPoints: false,
    tenderness: false,
    numbness: false,
    edema: false,
    swelling: false,
    reducedMotion: false,
    coldPack: false,
    hotPack: false,
    electStim: false,
    traction: false,
    massage: false,
    manipulation: false,
  },
  {
    spinalLevel: 't5_t6',
    side: null,
    sublux: false,
    muscleSpasm: false,
    triggerPoints: false,
    tenderness: false,
    numbness: false,
    edema: false,
    swelling: false,
    reducedMotion: false,
    coldPack: false,
    hotPack: false,
    electStim: false,
    traction: false,
    massage: false,
    manipulation: false,
  },
  {
    spinalLevel: 't6_t7',
    side: null,
    sublux: false,
    muscleSpasm: false,
    triggerPoints: false,
    tenderness: false,
    numbness: false,
    edema: false,
    swelling: false,
    reducedMotion: false,
    coldPack: false,
    hotPack: false,
    electStim: false,
    traction: false,
    massage: false,
    manipulation: false,
  },
  {
    spinalLevel: 't7_t8',
    side: null,
    sublux: false,
    muscleSpasm: false,
    triggerPoints: false,
    tenderness: false,
    numbness: false,
    edema: false,
    swelling: false,
    reducedMotion: false,
    coldPack: false,
    hotPack: false,
    electStim: false,
    traction: false,
    massage: false,
    manipulation: false,
  },
  {
    spinalLevel: 't8_t9',
    side: null,
    sublux: false,
    muscleSpasm: false,
    triggerPoints: false,
    tenderness: false,
    numbness: false,
    edema: false,
    swelling: false,
    reducedMotion: false,
    coldPack: false,
    hotPack: false,
    electStim: false,
    traction: false,
    massage: false,
    manipulation: false,
  },
  {
    spinalLevel: 't9_t10',
    side: null,
    sublux: false,
    muscleSpasm: false,
    triggerPoints: false,
    tenderness: false,
    numbness: false,
    edema: false,
    swelling: false,
    reducedMotion: false,
    coldPack: false,
    hotPack: false,
    electStim: false,
    traction: false,
    massage: false,
    manipulation: false,
  },
  {
    spinalLevel: 't10_t11',
    side: null,
    sublux: false,
    muscleSpasm: false,
    triggerPoints: false,
    tenderness: false,
    numbness: false,
    edema: false,
    swelling: false,
    reducedMotion: false,
    coldPack: false,
    hotPack: false,
    electStim: false,
    traction: false,
    massage: false,
    manipulation: false,
  },
  {
    spinalLevel: 't11_t12',
    side: null,
    sublux: false,
    muscleSpasm: false,
    triggerPoints: false,
    tenderness: false,
    numbness: false,
    edema: false,
    swelling: false,
    reducedMotion: false,
    coldPack: false,
    hotPack: false,
    electStim: false,
    traction: false,
    massage: false,
    manipulation: false,
  },
  {
    spinalLevel: 't12_l1',
    side: null,
    sublux: false,
    muscleSpasm: false,
    triggerPoints: false,
    tenderness: false,
    numbness: false,
    edema: false,
    swelling: false,
    reducedMotion: false,
    coldPack: false,
    hotPack: false,
    electStim: false,
    traction: false,
    massage: false,
    manipulation: false,
  },
  {
    spinalLevel: 'l1_l2',
    side: null,
    sublux: false,
    muscleSpasm: false,
    triggerPoints: false,
    tenderness: false,
    numbness: false,
    edema: false,
    swelling: false,
    reducedMotion: false,
    coldPack: false,
    hotPack: false,
    electStim: false,
    traction: false,
    massage: false,
    manipulation: false,
  },
  {
    spinalLevel: 'l2_l3',
    side: null,
    sublux: false,
    muscleSpasm: false,
    triggerPoints: false,
    tenderness: false,
    numbness: false,
    edema: false,
    swelling: false,
    reducedMotion: false,
    coldPack: false,
    hotPack: false,
    electStim: false,
    traction: false,
    massage: false,
    manipulation: false,
  },
  {
    spinalLevel: 'l3_l4',
    side: null,
    sublux: false,
    muscleSpasm: false,
    triggerPoints: false,
    tenderness: false,
    numbness: false,
    edema: false,
    swelling: false,
    reducedMotion: false,
    coldPack: false,
    hotPack: false,
    electStim: false,
    traction: false,
    massage: false,
    manipulation: false,
  },
  {
    spinalLevel: 'l4_l5',
    side: null,
    sublux: false,
    muscleSpasm: false,
    triggerPoints: false,
    tenderness: false,
    numbness: false,
    edema: false,
    swelling: false,
    reducedMotion: false,
    coldPack: false,
    hotPack: false,
    electStim: false,
    traction: false,
    massage: false,
    manipulation: false,
  },
  {
    spinalLevel: 'l5_s1',
    side: null,
    sublux: false,
    muscleSpasm: false,
    triggerPoints: false,
    tenderness: false,
    numbness: false,
    edema: false,
    swelling: false,
    reducedMotion: false,
    coldPack: false,
    hotPack: false,
    electStim: false,
    traction: false,
    massage: false,
    manipulation: false,
  },
  {
    spinalLevel: 's1_s2',
    side: null,
    sublux: false,
    muscleSpasm: false,
    triggerPoints: false,
    tenderness: false,
    numbness: false,
    edema: false,
    swelling: false,
    reducedMotion: false,
    coldPack: false,
    hotPack: false,
    electStim: false,
    traction: false,
    massage: false,
    manipulation: false,
  },
  {
    spinalLevel: 's2_s3',
    side: null,
    sublux: false,
    muscleSpasm: false,
    triggerPoints: false,
    tenderness: false,
    numbness: false,
    edema: false,
    swelling: false,
    reducedMotion: false,
    coldPack: false,
    hotPack: false,
    electStim: false,
    traction: false,
    massage: false,
    manipulation: false,
  },
  {
    spinalLevel: 's3_s4',
    side: null,
    sublux: false,
    muscleSpasm: false,
    triggerPoints: false,
    tenderness: false,
    numbness: false,
    edema: false,
    swelling: false,
    reducedMotion: false,
    coldPack: false,
    hotPack: false,
    electStim: false,
    traction: false,
    massage: false,
    manipulation: false,
  },
  {
    spinalLevel: 's4_s5',
    side: null,
    sublux: false,
    muscleSpasm: false,
    triggerPoints: false,
    tenderness: false,
    numbness: false,
    edema: false,
    swelling: false,
    reducedMotion: false,
    coldPack: false,
    hotPack: false,
    electStim: false,
    traction: false,
    massage: false,
    manipulation: false,
  },
  {
    spinalLevel: 's5_',
    side: null,
    sublux: false,
    muscleSpasm: false,
    triggerPoints: false,
    tenderness: false,
    numbness: false,
    edema: false,
    swelling: false,
    reducedMotion: false,
    coldPack: false,
    hotPack: false,
    electStim: false,
    traction: false,
    massage: false,
    manipulation: false,
  },
];
